import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { loadMessages } from "@luna/i18n/next/load-messages";
import { notFound } from "next/navigation";
import { supportedLngs } from "@luna/i18n/config";
import "../globals.css";
import { QueryProviders } from "@luna/queries";
import { SupportedLocale } from "../../../../packages/i18n/src/messages-manifest";

export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!supportedLngs.includes(locale as SupportedLocale)) {
    notFound();
  }

  const messages = await loadMessages(locale);

  return (
    <html lang={locale}>
      <body className={`overflow-y-hidden antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <QueryProviders>{children}</QueryProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
