// This file is auto-generated by scripts/generate-manifest.js
// Do not edit this file manually

export const MESSAGES = {
  en: {
    auth: () => import("../messages/en/auth.json"),
    calendar: () => import("../messages/en/calendar.json"),
    common: () => import("../messages/en/common.json"),
    feedback: () => import("../messages/en/feedback.json"),
    homework: () => import("../messages/en/homework.json"),
    lessons: () => import("../messages/en/lessons.json"),
    userMenu: () => import("../messages/en/userMenu.json"),
  },
  ko: {
    auth: () => import("../messages/ko/auth.json"),
    calendar: () => import("../messages/ko/calendar.json"),
    common: () => import("../messages/ko/common.json"),
    feedback: () => import("../messages/ko/feedback.json"),
    homework: () => import("../messages/ko/homework.json"),
    lessons: () => import("../messages/ko/lessons.json"),
    userMenu: () => import("../messages/ko/userMenu.json"),
  },
} as const;

export type MessageManifest = typeof MESSAGES;
export type SupportedLocale = keyof MessageManifest;
export type NamespaceOf<L extends SupportedLocale> = keyof MessageManifest[L];
